
SELECT Fname, Minit,Lname FROM EMPLOYEE WHERE Salary > (SELECT AVG(Salary) FROM EMPLOYEE);

SELECT Fname, Minit, Lname FROM EMPLOYEE WHERE Ssn NOT IN (SELECT DISTINCT Ssn FROM EMPLOYEE AS E JOIN DEPENDENT AS D ON E.Ssn = D.Essn) AND Ssn IN (select DISTINCT Super_Ssn from EMPLOYEE WHERE Super_ssn != 0);

SELECT Fname, Minit, Lname, (SELECT Salary/SUM(Hours) FROM WORKS_ON WHERE Essn = Ssn) AS throughput FROM EMPLOYEE ORDER BY throughput DESC;

SELECT D.DNAME, Avg(THROUGHPUT) FROM (SELECT  (E.SALARY/SUM(W.HOURS)) AS THROUGHPUT, DNO  FROM EMPLOYEE AS E INNER JOIN WORKS_ON AS W WHERE E.SSN = W.ESSN  GROUP BY ESSN) AS T INNER JOIN DEPARTMENT AS D WHERE D.DNUMBER = T.DNO GROUP BY D.DNAME ORDER BY AVG(T.THROUGHPUT)DESC;

Select Pname, COUNT(Essn) AS Employee_Count FROM PROJECT, WORKS_ON WHERE Pnumber = Pno GROUP BY Pname ORDER BY Employee_Count DESC;

Select Dno, count(Ssn) from EMPLOYEE where Dno in (select Dno from EMPLOYEE group by Dno having count(Ssn) >3) and Salary>37000 group by Dno;

SELECT Fname, Minit, Lname FROM EMPLOYEE WHERE Ssn NOT IN (SELECT Essn FROM WORKS_ON WHERE Pno = 1 OR Pno = 2);

SELECT Fname, Minit, Lname FROM EMPLOYEE WHERE Dno = (SELECT Dno FROM EMPLOYEE WHERE Salary = (SELECT MAX(Salary) FROM EMPLOYEE));

SELECT Fname, Minit, Lname FROM EMPLOYEE WHERE Super_ssn IN (SELECT Ssn FROM EMPLOYEE WHERE Super_ssn = '888665555');

SELECT Fname, Minit, Lname FROM EMPLOYEE WHERE Salary > (SELECT Salary FROM EMPLOYEE ORDER BY Salary ASC LIMIT 1) + 10000;


